### ISSUE TITLE
✅ (discentes) bolsistas cnpq: link

### ISSUE THREAD

**Issue by GustavoScaramussa** [COPLIN-UFSM/prpgp#11]
"bolsas CNPq tem que garimpar"... Tentar agrupar os bolsistas CNPQ por PPG através da mineração dos dados e incluí-los no Power Bi.
https://dados.gov.br/dados/organizacoes/visualizar/conselho-nacional-de-desenvolvimento-cientifico-e-tecnologico

**Comment by henryzord** [comment]
Bolsas cnpq adicionadas ao painel
